### ISSUE TITLE
Any version above 1.0.1 causes a crash when opening the Creative gui.

### ISSUE THREAD

**Issue by MagmaBro123** [c0508383/Backhand#21]
Title. Ping me on Discord when you're online.

https://pastebin.com/XpBMEG6b
Mods in report.

EDIT: This is caused by Already Decorating Fix.

**Comment by TCLProject** [comment]
> EDIT: This is caused by Already Decorating Fix. See TCL's server, and ping him about this.
This is an erroneous notion. I have tried to explain it to you, but I feel the need to repeat myself here.
Already Decorating Fix has nothing to do with this crash - it consists of about 50 lines of code, and none of it touch anything to do with inventories.
From what I see, this crash is likely caused by the lack of a '!= null' check in the right place, but I'll leave this to Louis to figure out.

**Comment by c0508383** [comment]
Fixed! It was a problem with an access transformer.
